version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    devices:
      - /dev/vchiq:/dev/vchiq
    container_name: jellyfin1
    user: 1000:1000
    network_mode: "host"
    privileged: true
    volumes:
      - /mnt/usbdrive/config:/config
      - /mnt/usbdrive/cache:/cache
      - /mnt/usbdrive/media:/media
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=192.168.1.248
